---

- name: jenkins restart
  service: name=jenkins state=restarted
  sudo: yes
  
- name: jenkins update jobs
  command: "{{jenkins_home}}/jobs/job.sh {{item.item.name}}"
  sudo_user: "{{ jenkins_user }}"
  when: item.changed
  with_items: jenkins_jobs_changed.results

- name: jenkins reload configuration
  command: java -jar {{jenkins_home}}/jenkins-cli.jar -s http://{{jenkins_http_host}}:{{jenkins_http_port}}{{jenkins_prefix}} reload-configuration
  sudo_user: "{{ jenkins_user }}"
  register: jenkins_reload
  until: jenkins_reload.rc == 0
  retries: 10
  delay: 10

- name: nginx reload
  service: name=nginx state=reloaded
  sudo: yes
  
- name: apache restart
  service: name=apache2 state=restarted
  sudo: yes
  
